### PR TITLE
Fix some tools safe strings

### PR DESCRIPTION
**Pull request by lulol**
For get_range.ml, mld_hash.ml and svg_converter.ml:
- Fix deprecated String.create alias of Bytes.create
- Convert Bytes.to_string

### CODE REVIEW

**Comment by lulol** [comment]
Still, for some svg icons in the icons/rsvg directory the *_svg.ml files are not generated.
```
splash_screen.svg
menu_downloads.svg
menu_networks.svg
menu_servers.svg
```
Adding them manually seems to work.

**Comment by ygrek** [comment]
sorry, didn't see this PR and fixed these another way (ftr Bytes.of_string is always safe but costly - creates memory copy)

**Comment by ygrek** [comment]
@lulol for the missing icons i somehow had the same issue, fixed with removing all ml_icons files before build. If there is reproduction case why this happens - please open new bug, otherwise I explain it by the leftovers from previous failed builds or smth.

**Comment by lulol** [comment]
Didn't find any issue with the current master, that builds mlnet and gui on ubuntu-22.04 without errors.

**Pull request closed without merging**
