### PR TITLE
gcc 10.x compatibility for ocaml-4.01.0

### PR DESCRIPTION
**Pull request by HinTak**
fixes https://github.com/ygrek/mldonkey/issues/49

### CODE REVIEW

**Comment by ygrek** [comment]
My plan is to upgrade mldonkey to build with opam and latest ocaml compilers, so this PR will not be needed. Will keep this open as a reminder while it is not done.

**Comment by HinTak** [comment]
There is no harm merging this - as far as I see the patches are matched to the ocaml version so is automatically dropped when you moved to the latest ocaml.

Small related issue that I filed elsewhere about unsafe strings (distro ships latest ocaml that way).

**Comment by ygrek** [comment]
You are right.
Thanks

**Comment by HinTak** [comment]
Thanks!

**Pull request merged**
